config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {
      sign_in: 'login', registration: 'cadastro'
  }

  resources :bookstores, :categories, :books
  resources :admin, :signature
  
  root 'main#index'

  get '/cadastro', to: 'users#new', as: 'users'  
  get '/logout', to: 'users#logout'
  get '/pagamento', to: 'signature#payment'
  get '/profile/:id/edit', to: 'users#edit', as: 'edit_user'    
  get 'profile/:id/address', to: 'address#edit', as: 'edit_address'  
  get '/profile/:id', to: 'users#profile', as: 'profile'
  get '/my_books/:id', to: 'users#my_books', as: 'my_books'
  get '/catalog' => 'books#catalog', as: 'books_catalog'
  get '/packages' => 'admin#packages', as: 'admin_packages'
  get '/boleto_payment' => 'signature#boleto_payment'
  get '/credit_card_payment' => 'signature#credit_card_payment'
  post '/cadastro', to: 'users#create'
  post 'bookstores/search' => 'bookstores#search', as: 'search_bookstores'
  post 'books/search' => 'books#search', as: 'search_books'
  post 'categories/search' => 'categories#search', as: 'search_categories'
  post '/credit_card_payment' => 'signature#process_payment_credit_card'
  post '/boleto_payment' => 'signature#process_payment_boleto'
  post '/cadastro' => 'users#create'

  post '/signature/cancel_signature/:id' => 'signature#cancel_signature'
  post '/users/delete_user/:id' => 'users#delete_user'

  post '/' => 'main#store_signature'

  patch '/profile/:id/edit', to: 'users#update', as: 'update_user'
  patch 'profile/:id/address', to: 'address#update', as: 'address_update'  

  delete 'profile/:id', to: 'users#destroy', as: 'delete_user'

end

app/models/address.rb
class Address < ActiveRecord::Base

  # Relações
  belongs_to :user, dependent: :destroy

  # Validação
  validates :user_id, :zipcode, :street, :presence => true

end

app/models/book.rb
class Book < ActiveRecord::Base



    has_many :user_books, :class_name => 'UserBook'
    has_many :package_books, :class_name => 'PackageBook'
    has_many :bookstore_books, :class_name => 'BookstoreBook'
    has_many :book_categories, :class_name => 'BookCategory'
end

app/models/book_category.rb
class BookCategory < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :category, :class_name => 'Category', :foreign_key => :id_category
end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base



    has_many :user_books, :class_name => 'UserBook'
    has_many :orders, :class_name => 'Order'
    has_many :bookstore_books, :class_name => 'BookstoreBook'
end

app/models/bookstore_book.rb
class BookstoreBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :bookstore, :class_name => 'Bookstore', :foreign_key => :id_bookstore
end

app/models/category.rb
class Category < ActiveRecord::Base



    has_many :user_preferences, :class_name => 'UserPreference'
    has_many :book_categories, :class_name => 'BookCategory'
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base

    has_many :payments, :class_name => 'Payment'
    belongs_to :user, :class_name => 'User', :foreign_key => :user_id

end

app/models/order.rb
class Order < ActiveRecord::Base



    belongs_to :bookstore, :class_name => 'Bookstore', :foreign_key => :id_bookstore
    has_many :packages, :class_name => 'Package'
end

app/models/package.rb
class Package < ActiveRecord::Base



    belongs_to :order, :class_name => 'Order', :foreign_key => :id_order
    has_many :package_books, :class_name => 'PackageBook'
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/package_book.rb
class PackageBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :package, :class_name => 'Package', :foreign_key => :id_package
end

app/models/payment.rb
class Payment < ActiveRecord::Base



    belongs_to :credit_card, :class_name => 'CreditCard', :foreign_key => :id_credit_card
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/periodicity.rb
class Periodicity < ActiveRecord::Base



end

app/models/signature.rb
class Signature < ActiveRecord::Base
    belongs_to :user, :class_name => 'User', :foreign_key => :user_id
end

app/models/support_ticket.rb
class SupportTicket < ActiveRecord::Base


    self.inheritance_column = :ruby_type
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    enum gender: [ :masculino, :feminino ]

    has_many :addresses, :class_name => 'Address'
    accepts_nested_attributes_for :addresses

    has_many :user_preferences, :class_name => 'UserPreference'
    has_many :user_books, :class_name => 'UserBook'
    has_many :support_tickets, :class_name => 'SupportTicket'
    has_many :signatures, :class_name => 'Signature'
    has_many :payments, :class_name => 'Payment'
    has_many :packages, :class_name => 'Package'
    has_many :credit_cards, :class_name => 'CreditCard'

    validates :password, confirmation: true

  validates :name, :cpf, :email, :birth_date, :gender, presence: true
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :user, :class_name => 'Bookstore', :foreign_key => :id_user
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def full_address
		if @user_addresses.count == 0
			"Endereço não informado"
		else
			@user_addresses.each do |addr|
				if addr.main == true
					return addr.street + " " + addr.city
				end
			end
		end
	end
	
end

app/views/admin/create_book.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->
<html>
	<head>
		<title>SejaLivro - Assinatura Literária</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div class="container">
						<!-- Header -->
							<header id="header">
								<div class="inner">
									<!-- Logo -->
										<h1><a href="index.html" id="logo">SejaLivro</a></h1>
									<!-- Nav -->
										<nav id="nav">
											<ul>
												<li> 
													<a href="profile.html">Meu Perfil</a>
												</li>
												<li>
													<a href="my_books.html">Meus livros</a>
												</li>
												<li>
													<a href="logout.html">Sair</a>
												</li>
											</ul>
										</nav>
								</div>
							</header>
					</div>
				</div>
				
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
							<section class="container box feature1">
									<div class="row" id="createBook">
										<div class="12u">
											<header>
												<h2>Adicionar item</h2>
											</header>
										</div>
									</div>
							</section>
								<div class="row">
									<div class="6u 12u(mobile)">
										<form>
											<fieldset>
												<label for="name"><span>Nome </span><input type="text" id="name" /></label>
												<label for="isbn"><span>ISBN </span><input type="text" id="isbn" /></label>
												<label for="author"><span>Autor </span><input type="text" id="author" /></label>
											</fieldset>
										</form>
									</div>
									<div class="6u 12u(mobile)">
										<form>
											<fieldset>
												<label for="year"><span>Ano </span><input type="text" id="year" /></label>
												<label for="language"><span>Idioma </span><input type="text" id="language" /></label>
												<label for="publisher"><span>Editora </span><input type="text" id="publisher" /></label>
											</fieldset>
										</form>
									</div>
								</div>
								<section class="container box feature1">
									<div class="row">
										<div class="12u">
											<span> <a href="view_book.html.erb" class="button">Salvar</a>
											<a href="book_list.html" class="button">Cancelar</a> 
											</span>
										</div>
									</div>
								</section>
							</div>
						</div>
					</div>
				</div>

			<!-- Footer Wrapper -->
				<div id="footer-wrapper">
					<footer id="footer" class="container">
						<div class="row">
							<div class="6u 12u(mobile)"> 
								<!-- About -->
									<section>
										<h2><strong>SejaLivro</strong></h2>
										<p>Olá! Este é o <strong>SejaLivro</strong>, um serviço de assinatura de livros. Você adquire um pacote por valor fixo e nós nos encarregamos de te surpreender com novas leituras, sem qualquer dor de cabeça e entrega em sua casa!</p>
										<a href="#simular" class="button icon fa-arrow-circle-right" style="align: center;">Simular Assinatura</a>
									</section>
							</div>
							
							<div class="6u 12u(mobile)">
								<!-- Contact -->
									<section>
										<h2>Redes Sociais</h2>
										<div>
											<div class="row">
												<div class="6u 12u(mobile)">
													<dl class="contact">
														<dt>Twitter</dt>
														<dd><a href="#">@SejaLivro</a></dd>
														<dt>Facebook</dt>
														<dd><a href="#">facebook.com/SejaLivro</a></dd>
														<dt>WWW</dt>
														<dd><a href="#">sejalivro.com</a></dd>
														<dt>Email</dt>
														<dd><a href="#">contato@sejalivro.com</a></dd>
													</dl>
												</div>
												<div class="6u 12u(mobile)">
													<dl class="contact">
														<dt>Endereço</dt>
														<dd>
															Av. Luciano Gualberto, 314, Cid. Universitária<br />
															São Paulo, SP 01300-7800<br />
															Brasil
														</dd>
														<dt>Telefone</dt>
														<dd>(11) 0800-9999</dd>
													</dl>
												</div>
											</div>
										</div>
									</section>

							</div>
						</div>
						<div class="row">
							<div class="12u">
								<div id="copyright">
									<ul class="menu">
										<li>&copy; All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
									</ul>
								</div>
							</div>
						</div>
					</footer>
				</div>

		</div>

		<!-- Scripts -->

			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/admin/index.html.erb
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div class="container">
						<!-- Header -->
            <% if user_signed_in? %>
                <%= render 'main/login_top_menu' %>
            <% else %>
                <%= render 'main/logout_top_menu' %>
            <% end %>
					</div>
				</div>
				
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
							<section class="container box feature1">
									<div class="row" id="adminIndex">
										<div class="12u">
											<header>
												<h2>Gerenciamento</h2>
											</header>
											<p><%= link_to "Gerenciar Livros", books_path, :class => "button" %> </p>
											<p><%= link_to "Gerenciar Categorias", categories_path, :class => "button" %> </p>
											<p><%= link_to "Gerenciar Livrarias", bookstores_path, :class => "button" %> </p>
										</div>
									</div>
								</section>								
							</div>
						</div>
					</div>
				</div>

			<!-- Footer Wrapper -->
      <%= render 'main/footer' %>

		</div>

app/views/admin/packages.html.erb
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div class="container">
						<!-- Header -->
            <% if user_signed_in? %>
                <%= render 'main/login_top_menu' %>
            <% else %>
                <%= render 'main/logout_top_menu' %>
            <% end %>
					</div>
				</div>
				
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
							<section class="container box feature1">
									<div class="row" id="adminIndex">
										<div class="12u">
											<header>
												<h2>Gerenciamento - Gerenciar Pacotes</h2>
											</header>
											   <h1>Próximas bateladas: </h1>
											   <% pers = [5]
											   	  (0..4).each do |i| 
											   	  	pers[i] = 0
											   	  end	
											   %>
	   											<% @users.each do |user| 
	   												if user.signatures.count > 0
	   													user.signatures.each do |signature|
											   				@sig_per = signature.periodicity_id
										   				end
										   			pers[@sig_per] += 1
										   			end
											    end %>
											      Pacotes para daqui 7: <%= pers[0] %>
											      <br>Pacotes para daqui 15 dias: <%= pers[0] + pers[1]%>
											      <br>Pacotes para daqui 30 dias: <%= pers[0] + pers[1] + pers[2] %>
											<p><%= link_to "Ver compras", books_path, :class => "button" %> </p>
											<p><%= link_to "Gerenciar Categorias", categories_path, :class => "button" %> </p>
											<p><%= link_to "Gerenciar Livrarias", bookstores_path, :class => "button" %> </p>
											<p><%= link_to "Gerenciar Pacotes", bookstores_path, :class => "button" %> </p>
										</div>
									</div>
								</section>								
							</div>
						</div>
					</div>
				</div>

			<!-- Footer Wrapper -->
      <%= render 'main/footer' %>

		</div>

app/views/admin/view_book.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->
<html>
	<head>
		<title>SejaLivro - Assinatura Literária</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div class="container">
						<!-- Header -->
							<header id="header">
								<div class="inner">
									<!-- Logo -->
										<h1><a href="index.html" id="logo">SejaLivro</a></h1>
									<!-- Nav -->
										<nav id="nav">
											<ul>
												<li> 
													<a href="profile.html">Meu Perfil</a>
												</li>
												<li>
													<a href="my_books.html">Meus livros</a>
												</li>
												<li>
													<a href="logout.html">Sair</a>
												</li>
											</ul>
										</nav>
								</div>
							</header>
					</div>
				</div>
				
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
							<section class="container box feature1">
									<div class="row" id="viewBook">
										<div class="12u">
											<header>
												<h2>Visualizar item</h2>
											</header>
										</div>
									</div>
							</section>
								<div class="row">
									<div class="6u 12u(mobile)">
										<a href="#" class="image centered"><img src="images/overcoat.jpg" alt="" height=400 width=auto /></a>
									</div>
									<div class="6u 12u(mobile)">
										<dl class="inline">
											<dt>ID:</dt>
											<dd>ID do Livro</dd>
											<dt>Nome:</dt>
											<dd>Nome do Livro</dd>
											<dt>ISBN:</dt>
											<dd>ISBN do livro</dd>
											<dt>Autor:</dt>
											<dd>Autor do Livro</dd>
											<dt>Ano:</dt>
											<dd>Ano de publicação</dd>
											<dt>Idioma:</dt>
											<dd>Idioma do livro</dd>
											<dt>Editora:</dt>
											<dd>Editora do Livro</dd>
										</dl>
									</div>
								</div>
								<section class="container box feature1">
									<div class="row">
										<div class="12u">
											<span> <a href="book_list.html" class="button">Voltar</a>  
											  <a href="create_book.html" class="button">Editar</a>
											  <a href="#" class="button">Excluir</a> 
											  </span>
										</div>
									</div>
								</section>
							</div>
						</div>
					</div>
				</div>
				
				<!--<div class="12u">
											<header>
												<h2></h2>
											</header>
												
											<footer>
											  
											</footer>	
										</div>
									</div>
							  </section>
							</div>
						</div>
					</div>
				</div>-->

			<!-- Footer Wrapper -->
				<div id="footer-wrapper">
					<footer id="footer" class="container">
						<div class="row">
							<div class="6u 12u(mobile)"> 
								<!-- About -->
									<section>
										<h2><strong>SejaLivro</strong></h2>
										<p>Olá! Este é o <strong>SejaLivro</strong>, um serviço de assinatura de livros. Você adquire um pacote por valor fixo e nós nos encarregamos de te surpreender com novas leituras, sem qualquer dor de cabeça e entrega em sua casa!</p>
										<a href="#simular" class="button icon fa-arrow-circle-right" style="align: center;">Simular Assinatura</a>
									</section>
							</div>
							
							<div class="6u 12u(mobile)">
								<!-- Contact -->
									<section>
										<h2>Redes Sociais</h2>
										<div>
											<div class="row">
												<div class="6u 12u(mobile)">
													<dl class="contact">
														<dt>Twitter</dt>
														<dd><a href="#">@SejaLivro</a></dd>
														<dt>Facebook</dt>
														<dd><a href="#">facebook.com/SejaLivro</a></dd>
														<dt>WWW</dt>
														<dd><a href="#">sejalivro.com</a></dd>
														<dt>Email</dt>
														<dd><a href="#">contato@sejalivro.com</a></dd>
													</dl>
												</div>
												<div class="6u 12u(mobile)">
													<dl class="contact">
														<dt>Endereço</dt>
														<dd>
															Av. Luciano Gualberto, 314, Cid. Universitária<br />
															São Paulo, SP 01300-7800<br />
															Brasil
														</dd>
														<dt>Telefone</dt>
														<dd>(11) 0800-9999</dd>
													</dl>
												</div>
											</div>
										</div>
									</section>

							</div>
						</div>
						<div class="row">
							<div class="12u">
								<div id="copyright">
									<ul class="menu">
										<li>&copy; All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
									</ul>
								</div>
							</div>
						</div>
					</footer>
				</div>

		</div>

		<!-- Scripts -->

			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html xmlns:style="http://www.w3.org/1999/xhtml">
  <head>
    <title>SejaLivro - Assinatura Literária</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="/assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="/assets/css/main.css" />
    <!--[if lte IE 8]><link rel="stylesheet" href="/assets/css/ie8.css" /><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="/assets/css/ie9.css" /><![endif]-->
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
    </script>

  </head>

  <body>
    <%= yield %>

    <!-- Scripts -->

    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/jquery.dropotron.min.js"></script>
    <script src="/assets/js/skel.min.js"></script>
    <script src="/assets/js/skel-viewport.min.js"></script>
    <script src="/assets/js/util.js"></script>
    <!--[if lte IE 8]><script src="/assets/js/ie/respond.min.js"></script><![endif]-->
    <script src="/assets/js/main.js"></script>

  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sejalivro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>