config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {
      sign_in: 'login', registration: 'cadastro'
  }

  resources :bookstores, :categories, :books
  resources :admin, :signature
  
  root 'main#index'

  get '/cadastro', to: 'users#new', as: 'users'  
  get '/logout', to: 'users#logout'
  get '/pagamento', to: 'signature#payment'
  get '/profile/:id/edit', to: 'users#edit', as: 'edit_user'    
  get 'profile/:id/address', to: 'address#edit', as: 'edit_address'  
  get '/profile/:id', to: 'users#profile', as: 'profile'
  get '/my_books/:id', to: 'users#my_books', as: 'my_books'
  get '/catalog' => 'books#catalog', as: 'books_catalog'
  get '/packages' => 'admin#packages', as: 'admin_packages'
  get '/boleto_payment' => 'signature#boleto_payment'
  get '/credit_card_payment' => 'signature#credit_card_payment'
  post '/cadastro', to: 'users#create'
  post 'bookstores/search' => 'bookstores#search', as: 'search_bookstores'
  post 'books/search' => 'books#search', as: 'search_books'
  post 'categories/search' => 'categories#search', as: 'search_categories'
  post '/credit_card_payment' => 'signature#process_payment_credit_card'
  post '/boleto_payment' => 'signature#process_payment_boleto'
  post '/cadastro' => 'users#create'

  post '/signature/cancel_signature/:id' => 'signature#cancel_signature'
  post '/users/delete_user/:id' => 'users#delete_user'

  post '/' => 'main#store_signature'

  patch '/profile/:id/edit', to: 'users#update', as: 'update_user'
  patch 'profile/:id/address', to: 'address#update', as: 'address_update'  

  delete 'profile/:id', to: 'users#destroy', as: 'delete_user'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    enum gender: [ :masculino, :feminino ]

    has_many :addresses, :class_name => 'Address'
    accepts_nested_attributes_for :addresses

    has_many :user_preferences, :class_name => 'UserPreference'
    has_many :user_books, :class_name => 'UserBook'
    has_many :support_tickets, :class_name => 'SupportTicket'
    has_many :signatures, :class_name => 'Signature'
    has_many :payments, :class_name => 'Payment'
    has_many :packages, :class_name => 'Package'
    has_many :credit_cards, :class_name => 'CreditCard'

    validates :password, confirmation: true

  validates :name, :cpf, :email, :birth_date, :gender, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Método que define o que ocorre quando abre-se a tela para cadastrar usuário
  # GET /users/register
  def new
    @user = User.new
    1.times { @user.addresses.build}
  end

  def logout
    cookies.delete :waiting_for_payment

    sign_out :user
    redirect_to root_path
  end

  # POST /users
  # POST /users.json
  def create
    # Convertendo genero inteiro
    params[:user][:gender] = params[:user][:gender].to_i

    # Build nos parametros
    @user = User.new(user_params)
    @user.addresses = []

    if params[:user]["birth_date(1i)"] != '' && params[:user]["birth_date(2i)"] != '' && params[:user]["birth_date(3i)"] != ''
      @user.birth_date = Date.new(params[:user]["birth_date(1i)"].to_i,params[:user]["birth_date(2i)"].to_i,params[:user]["birth_date(3i)"].to_i)
    end

    respond_to do |format|
      if valid_address(user_params) && @user.save
        @user.addresses.build(user_params[:addresses_attributes]["0"])
        @user.save

        format.html { redirect_to new_user_session_path, notice: 'Usuário criado!' }
        format.json { render new_user_session_path, status: :created, location: @user }
      else
        1.times { @user.addresses.build}
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def valid_address(params)
    result = true

    if params[:addresses_attributes]["0"][:country].empty?
      @user.errors.add(:country, "não pode ficar em branco.")
      result = false
    end
    if params[:addresses_attributes]["0"][:city].empty?
      @user.errors.add(:city, "não pode ficar em branco.")
      result = false
    end
    if params[:addresses_attributes]["0"][:state].empty?
      @user.errors.add(:state, "não pode ficar em branco.")
      result = false
    end
    if params[:addresses_attributes]["0"][:quarter].empty?
      @user.errors.add(:quarter, "não pode ficar em branco.")
      result = false
    end
    if params[:addresses_attributes]["0"][:zipcode].empty?
      @user.errors.add(:zipcode, "não pode ficar em branco.")
      result = false
    end
    if params[:addresses_attributes]["0"][:street].empty?
      @user.errors.add(:street, "não pode ficar em branco.")
      result = false
    end

    result
  end

  def update
    # Convertendo genero inteiro
    params[:user][:gender] = params[:user][:gender].to_i

    # Build nos parametros
    @user = User.find(params[:id])        

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to action: :profile }
        format.json { render action: :profile, status: :created, location: @user }
      else
        format.html { render action: :profile }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Método que define o que ocorre quando abre-se a tela de perfil
  # GET /profile/:id
  def profile
    if user_signed_in? && current_user.id.to_s == params[:id]
      @user = User.find(params[:id])
      @user_signatures = @user.signatures
      @periodicity = Periodicity.all
      @user_addresses = @user.addresses
      @user_books = @user.user_books
    else
      redirect_to root_path
    end
  end

  def my_books
    if user_signed_in? && current_user.id.to_s == params[:id]
      @user = User.find(params[:id])
      @user_books = @user.user_books
      @user_prefs = @user.user_preferences
    else
      redirect_to root_path
    end
  end

  def delete_user
    sign_out :user

    Signature.where(user_id: params[:id].to_i).destroy_all
    CreditCard.where(user_id: params[:id].to_i).destroy_all
    Address.where(user_id: params[:id].to_i).destroy_all

    User.delete(params[:id].to_i)

    redirect_to root_path
  end

  def index
    redirect_to new_user_path
  end

  def edit
    @user = User.find(params[:id])

    if @user.nil?
      redirect_to action: :profile
    end    
  end

  def destroy
    #precisa implementar 
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :cpf, :email, :login, :birth_date, :gender, :password, :password_confirmation, :addresses_attributes => [ :zipcode, :city, :country, :state, :complement, :street, :quarter])
    end
end

app/helpers/users_helper.rb
module UsersHelper
	
	def full_address
		if @user_addresses.count == 0
			"Endereço não informado"
		else
			@user_addresses.each do |addr|
				if addr.main == true
					return addr.street + " " + addr.city
				end
			end
		end
	end
	
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :id => "form_cadastro" }) do |f| %>
    <div class="row">

      <% if @user.errors.any? %>
          <div class="12u">
            <ul>
              <li><b><%= pluralize(@user.errors.count, "erros") %> foram encontrados no preenchimento do formulário.</b></li>
              <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


      <div class="4u">
        <section>
          <header>
            <h3>Dados pessoais</h3>
          </header>
          <article>
            <fieldset>
              <div class="12u form-field"><%= f.text_field :name, placeholder: "Nome", id: 'nome' %></div>
              <div class="12u form-field"><%= f.text_field :cpf, placeholder: "CPF", id: 'cpf' %></div>
              <div class="12u form-label" style="text-align: left; margin-bottom: -20px;"><%= f.label "Gênero" %></div>
              <div class="12u form-field-labeled">
                <%= f.select(:gender) do %>
                    <% [['Masculino', 0], ['Feminino', 1]].each do |c| -%>
                        <%= content_tag(:option, c.first, value: c.last) %>
                    <% end %>
                <% end %>
              </div>

              <div class="12u form-label" style="text-align: left; margin-bottom: -20px;"> <%= f.label "Nascimento" %></div>
              <div class="12u form-field-labeled"><%= f.date_select :birth_date,  order: [:day, :month, :year], :start_year => 1900, :end_year => 2000, prompt: {day: 'Dia', month: 'Mês', year: 'Ano'}, use_month_numbers: true %></div>
            </fieldset>
          </article>
        </section>
      </div>

      <div class="4u">
        <section>
          <header>
            <h3>Endereço</h3>
          </header>
          <article>
            <fieldset>
              <%= f.fields_for :addresses do |ff| %>                  
                  <div class="12u form-field"><%= ff.text_field :country, placeholder: "País", id: 'pais' %></div>
                  <div class="12u form-field"><%= ff.text_field :zipcode, placeholder: "CEP", id: 'cep', onblur: "pesquisacep(this.value);" %></div>
                  <div class="12u form-field"><%= ff.text_field :city, placeholder: "Cidade", id: 'cidade' %></div>
                  <div class="12u form-field"><%= ff.text_field :state, placeholder: "Estado", id: 'uf' %></div>
                  <div class="12u form-field"><%= ff.text_field :quarter, placeholder: "Bairro", id: 'bairro' %></div>
                  <div class="12u form-field"><%= ff.text_field :street, placeholder: "Logradouro", id: 'rua' %></div>
                  <div class="12u form-field"><%= ff.text_field :complement, placeholder: "Complemento" %></div>
              <% end %>
            </fieldset>
          </article>
        </section>
      </div>

      <div class="4u">
        <section>
          <header>
            <h3>Cadastre uma senha</h3>
          </header>
          <article>

            <fieldset>
              <div class="12u form-field"><%= f.text_field :email, placeholder: "Email", id: 'email' %></div>
              <div class="12u form-field"><%= f.password_field :password, placeholder: "Senha", id: 'senha' %></div>
              <div class="12u form-field"><%= f.password_field :password_confirmation, placeholder: "Confirmação de Senha", id: 'conf_senha' %></div>
            </fieldset>
          </article>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="12u no-padding form-margin">
        <%= f.submit "Cadastrar", class: "button big icon fa-arrow-circle-right", id: 'cadastrar' %>
      </div>
    </div>

<% end %>

app/views/users/edit.html.erb
<div id="page-wrapper">

  <!-- Header -->
  <div id="header-wrapper">
    <div class="container">
      <% if user_signed_in? %>
          <%= render 'main/login_top_menu' %>
      <% else %>
          <%= render 'main/logout_top_menu' %>
      <% end %>
    </div>
  </div>

  <!-- Main Wrapper -->
  <div id="main-wrapper">
    <div class="wrapper style2">
      <div class="inner">

        <!-- Feature 1 -->
        <section class="container box feature1">


          <div class="12u" id="vantagens">
            <%= form_for(@user, :url => { action: :update }) do |f| %>
    <div class="row">

      <% if @user.errors.any? %>
          <div class="12u">
            <ul>
              <li><b><%= pluralize(@user.errors.count, "erros") %> foram encontrados no preenchimento do formulário.</b></li>
              <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


      <div class="12u">
        <section>        
          <header>
            <h3>Dados pessoais</h3>
          </header>
          <article>
            <fieldset>
              <label for="name" class="6u" style="text-align: left;"><span>Nome </span><%= f.text_field :name, id: 'nome' %></label>
              <label for="name" class="6u" style="text-align: left;"><span>CPF </span><%= f.text_field :cpf, id: 'cpf' %></label>
              <div class="6u form-label" style="text-align: left;"><%= f.label "Gênero" %></div>
              <div class="6u form-field-labeled">
                <%= f.select(:gender) do %>
                    <% [['Masculino', 0], ['Feminino', 1]].each do |c| -%>
                        <%= content_tag(:option, c.first, value: c.last) %>
                    <% end %>
                <% end %>
              </div>

              <div class="6u form-label" style="text-align: left; margin-bottom: -20px;"> <%= f.label "Nascimento" %></div>
              <div class="6u form-field-labeled"><%= f.date_select :birth_date,  order: [:day, :month, :year], :start_year => 1900, :end_year => 2000, prompt: {day: 'Dia', month: 'Mês', year: 'Ano'}, use_month_numbers: true %></div>
            </fieldset>
          </article>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="12u no-padding form-margin">
        <%= f.submit "Atualizar", class: "button icon fa-arrow-circle-right", id: 'atualizar' %>
      </div>
    </div>

<% end %>
          </div>
        </section>
      </div>
    </div>
  </div>

  <!-- Footer Wrapper -->
  <%= render 'main/footer' %>
  
  <script type="text/javascript">
    $(document).ready(function() { $('#atualizar').on('click', function(e){
      if (!validateUserUpdate())
          e.preventDefault();
    })
  });
  </script>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Todos os usuários') %>
<h1>Todos os usuários</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/my_books.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
  <body class="homepage">
    <div id="page-wrapper">

      <!-- Header -->
        <div id="header-wrapper" style="background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)), url('images/bg03.png'), url('images/bg02.png');">
          <div class="container">
            <!-- Header -->
            <%= render 'main/login_top_menu' %>
          </div>
        </div>

  <!-- Main Wrapper -->
  <div id="main-wrapper">
    <div class="wrapper style1">
      <div class="inner">
        <!-- Feature 1 -->
        <section class="container box feature1">
          <div class="css3-tabstrip">
            <div class="3u">
              <li>
                <input type="radio" name="css3-tabstrip-0" checked="checked" id="css3-tabstrip-0-0" /><label for="css3-tabstrip-0-0">Meus Livros</label>
                <div>
                   <header>
                        <h2>Biblioteca de <%= @user.name %></h2>
                    </header>
                  <div class="row" id="livros">
                          <% if @user_books.count == 0 %>
                            <span style="font-weight: bold;"> Não possui itens. </span><br>
                            <% else 
                              @user_books.each do |book| %>
                                <% b = Book.find(book.book_id) %> 
                                    <div class="1.5u 6u(mobile)">
                                      <%= image_tag("/images/books_cover/#{b.id}.jpg",:id => "capa") %><br>
                                      <span style="font-weight: bold;"> <%= b.name %></span><br>
                                      <span style="font-style: italic;"> <%= b.author %></span><br>
                                    </div>
                                  <% end %>
                                <% end %>
                  </div>
                  <div class="row" id="livros">
          
                  </div>
                </div>
              </li>
              <li>
              <input type="radio" name="css3-tabstrip-0" id="css3-tabstrip-0-1" /><label for="css3-tabstrip-0-1">Categorias</label>
              <div>
               <header>
                        <h2>Categorias prediletas de <%= @user.name %></h2>
                      </header>

                <div class="row" id="livros">
                          <% if @user_prefs.count == 0 %>
                            <span style="font-weight: bold;"> Não possui preferências. </span><br>
                            <% else 
                              @user_prefs.each do |pref| %>
                              <% c = Category.find(pref.preference_id) %> 
                                    <div class="1.5u 6u(mobile)">
                                      <img id="capa" src="/images/categories/#{pref.id}.jpg"/><br>
                                      <span style="font-weight: bold;"> <%= c.name %></span><br>
                                    </div>
                                  <% end %>
                                <% end %>
                  </div>
              </div>
            </li>
            </div>
            </ul>
          </div>
          <br><br><br>
          <div class="row">
            <div class="6u">
                <%= link_to "Voltar", "/profile/#{@user.id}", :class => "button big icon " %>
            </div>
            <div class="6u">
                <%= link_to "Importar", "/my_books/#{@user.id}", :class => "button big icon fa-arrow-circle-right" %>
            </div>
          </div>
        </section>

      </div>
    </div>
  </div>
</div>
  <!-- Footer Wrapper -->
      <%= render 'main/footer' %>
</body>
</html>

app/views/users/new.html.erb
<div id="page-wrapper">

  <!-- Header -->
  <div id="header-wrapper">
    <div class="container">
      <% if user_signed_in? %>
          <%= render 'main/login_top_menu' %>
      <% else %>
          <%= render 'main/logout_top_menu' %>
      <% end %>
    </div>
  </div>

  <!-- Main Wrapper -->
  <div id="main-wrapper">
    <div class="wrapper style2">
      <div class="inner">

        <!-- Feature 1 -->
        <section class="container box feature1">


          <div class="12u" id="vantagens">
            <%= render 'form', user: @user %>
          </div>



        </section>
      </div>
    </div>
  </div>

  <!-- Footer Wrapper -->
  <%= render 'main/footer' %>

  <script type="text/javascript">
    $(document).ready(function() { $('#cadastrar').on('click', function(e){
      if (!validateUser())
          e.preventDefault();
    })
  });
  </script>

</div>

app/views/users/profile.html.erb
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper" style="background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)), url('images/bg03.png'), url('images/bg02.png');">
					  
					<div class="container" style="background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5));"> 
						<!-- Header -->
          				<%= render 'main/login_top_menu' %>
					</div>
				</div>

			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style2">
						<div class="inner">

							<!-- Feature 1 -->
								<section class="container box feature1">
									<div class="row" id="vantagens">
										<div class="6u 12u(mobile)">
											<section>
												<header>
													<h3>Dados pessoais</h3>													
												</header>
												<a href="#" class="image featured"><img src="images/avatar.png" alt="" /></a>
												<dl class="inline">
													<dt>Nome:  </dt>
													<dd><%= @user.name %></dd>
													<dt>CPF: </dt>
													<dd><%= @user.cpf %></dd>
													<dt>Data de nascimento: </dt>
													<dd><%= @user.birth_date.to_formatted_s(:rfc822) %></dd>
													<dt>Endereço: </dt>
													<% address = @user.addresses.first %>
													<dd><%= address.street %>
													</dd>
													<dd><%= address.quarter %> </dd>
													<dd><%= address.zipcode + ', ' + address.city + ' - ' +  address.state%> </dd>
													<dd><%= address.country %> </dd>								
												</dl>
												<footer>
												  <p><%= link_to 'Atualizar dados', edit_user_path(@user), class: "button" %></p>
												  <p><%= link_to 'Atualizar endereço', edit_address_path(@user), class: "button" %></p>
												  <p><%= link_to 'Cancelar conta', "/users/delete_user/#{@user.id}", method: :post, class: "button" %></p>
												</footer>
											</section>
										</div>
										<div class="6u 12u(mobile)">
											<section>
												<header>
													<h3>Dados de assinatura</h3>
												</header>
												<% if @user_signatures.count == 0 %>
													 <dt>Status da assinatura: </dt>
													 <dd>Não possui assinaturas</dd>
													 <footer>
												  		<p><a href="/#simular" class="button" style="align: center;">Nova Assinatura</a></p>
													</footer>
												<% else %>
													<% @user_signatures.each do |signature| %>
														<dl class="inline">
															<dt>Status da assinatura: </dt>
															<dd> ATIVA </dd>
															<dt>Periodicidade: </dt>
															<dd><%= @periodicity.find(signature.periodicity_id).name %></dd>
														</dl>
                                <footer>
                                  <p>
                                    <%= link_to "Cancelar Assinatura", "/signature/cancel_signature/#{signature.id}", method: :post, class: "button" %>
                                  </p>
                                </footer>
													<% end %>
												<% end %>												
											</section>
										</div>
                    <!--
										<div class="6u 12u(mobile)">
											<section>
												<header>
													<h3>Biblioteca pessoal</h3>
												</header>
												<article>
													<div class="row" id="livros">
													<% if @user_books.count == 0 %>
														<span style="font-weight: bold;"> Não possui itens. </span><br>
														<% else
															if @user_books.count > 6
																max = 6
															else
																max = @user_books.count
															end
															@user_books[0..max].each do |book| %>
																<% b = Book.find(book.book_id) %>
											        			<div class="1.5u 6u(mobile)">
												        			<%= image_tag("/images/books_cover/#{b.id}.jpg",:id => "capa") %><br>
	        														<span style="font-weight: bold;"> <%= b.name %></span><br>
							        								<span style="font-style: italic;"> <%= b.author %></span><br>
										        				</div>
									        				<% end %>
									        			<% end %>
    												</div>
												</article>
												<footer>
												<%= link_to "Ver todos", "/my_books/#{@user.id}", :class => "button" %>
												</footer>
											</section>
										</div> -->
									</div>
								</section>
							</div>
					</div>
				</div>

			<!-- Footer Wrapper -->
			<%= render 'main/footer' %>

app/views/users/register.html.erb
<h1>Register User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>