config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {
      sign_in: 'login', registration: 'cadastro'
  }

  resources :bookstores, :categories, :books
  resources :admin, :signature
  
  root 'main#index'

  get '/cadastro', to: 'users#new', as: 'users'  
  get '/logout', to: 'users#logout'
  get '/pagamento', to: 'signature#payment'
  get '/profile/:id/edit', to: 'users#edit', as: 'edit_user'    
  get 'profile/:id/address', to: 'address#edit', as: 'edit_address'  
  get '/profile/:id', to: 'users#profile', as: 'profile'
  get '/my_books/:id', to: 'users#my_books', as: 'my_books'
  get '/catalog' => 'books#catalog', as: 'books_catalog'
  get '/packages' => 'admin#packages', as: 'admin_packages'
  get '/boleto_payment' => 'signature#boleto_payment'
  get '/credit_card_payment' => 'signature#credit_card_payment'
  post '/cadastro', to: 'users#create'
  post 'bookstores/search' => 'bookstores#search', as: 'search_bookstores'
  post 'books/search' => 'books#search', as: 'search_books'
  post 'categories/search' => 'categories#search', as: 'search_categories'
  post '/credit_card_payment' => 'signature#process_payment_credit_card'
  post '/boleto_payment' => 'signature#process_payment_boleto'
  post '/cadastro' => 'users#create'

  post '/signature/cancel_signature/:id' => 'signature#cancel_signature'
  post '/users/delete_user/:id' => 'users#delete_user'

  post '/' => 'main#store_signature'

  patch '/profile/:id/edit', to: 'users#update', as: 'update_user'
  patch 'profile/:id/address', to: 'address#update', as: 'address_update'  

  delete 'profile/:id', to: 'users#destroy', as: 'delete_user'

end

app/models/address.rb
class Address < ActiveRecord::Base

  # Relações
  belongs_to :user, dependent: :destroy

  # Validação
  validates :user_id, :zipcode, :street, :presence => true

end

app/models/book.rb
class Book < ActiveRecord::Base



    has_many :user_books, :class_name => 'UserBook'
    has_many :package_books, :class_name => 'PackageBook'
    has_many :bookstore_books, :class_name => 'BookstoreBook'
    has_many :book_categories, :class_name => 'BookCategory'
end

app/models/book_category.rb
class BookCategory < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :category, :class_name => 'Category', :foreign_key => :id_category
end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base



    has_many :user_books, :class_name => 'UserBook'
    has_many :orders, :class_name => 'Order'
    has_many :bookstore_books, :class_name => 'BookstoreBook'
end

app/models/bookstore_book.rb
class BookstoreBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :bookstore, :class_name => 'Bookstore', :foreign_key => :id_bookstore
end

app/models/category.rb
class Category < ActiveRecord::Base



    has_many :user_preferences, :class_name => 'UserPreference'
    has_many :book_categories, :class_name => 'BookCategory'
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base

    has_many :payments, :class_name => 'Payment'
    belongs_to :user, :class_name => 'User', :foreign_key => :user_id

end

app/models/order.rb
class Order < ActiveRecord::Base



    belongs_to :bookstore, :class_name => 'Bookstore', :foreign_key => :id_bookstore
    has_many :packages, :class_name => 'Package'
end

app/models/package.rb
class Package < ActiveRecord::Base



    belongs_to :order, :class_name => 'Order', :foreign_key => :id_order
    has_many :package_books, :class_name => 'PackageBook'
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/package_book.rb
class PackageBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :package, :class_name => 'Package', :foreign_key => :id_package
end

app/models/payment.rb
class Payment < ActiveRecord::Base



    belongs_to :credit_card, :class_name => 'CreditCard', :foreign_key => :id_credit_card
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/periodicity.rb
class Periodicity < ActiveRecord::Base



end

app/models/signature.rb
class Signature < ActiveRecord::Base
    belongs_to :user, :class_name => 'User', :foreign_key => :user_id
end

app/models/support_ticket.rb
class SupportTicket < ActiveRecord::Base


    self.inheritance_column = :ruby_type
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    enum gender: [ :masculino, :feminino ]

    has_many :addresses, :class_name => 'Address'
    accepts_nested_attributes_for :addresses

    has_many :user_preferences, :class_name => 'UserPreference'
    has_many :user_books, :class_name => 'UserBook'
    has_many :support_tickets, :class_name => 'SupportTicket'
    has_many :signatures, :class_name => 'Signature'
    has_many :payments, :class_name => 'Payment'
    has_many :packages, :class_name => 'Package'
    has_many :credit_cards, :class_name => 'CreditCard'

    validates :password, confirmation: true

  validates :name, :cpf, :email, :birth_date, :gender, presence: true
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :user, :class_name => 'Bookstore', :foreign_key => :id_user
end

app/models/user_preference.rb
class UserPreference < ActiveRecord::Base
    belongs_to :category, :class_name => 'Category', :foreign_key => :category_id
    belongs_to :user, :class_name => 'User', :foreign_key => :user_id
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
    @categories = Category.all
  end

  def index
    @books = Book.all.order(:id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.nil?
      redirect_to books_path
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to action: :index }
        format.json { render :new, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to action: :index }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if book = Book.find(params[:id])
      book.destroy
      redirect_to books_path
    end
  end

  def search
    @q = "%#{params[:query]}%"
    @books = Book.where("lower(name) LIKE ?", @q.downcase).order(:id)
    render 'index'
  end

  def catalog
    @categories = Category.all
  end

  

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:name, :isbn, :author, :language, :publisher, :year)
  end

end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def full_address
		if @user_addresses.count == 0
			"Endereço não informado"
		else
			@user_addresses.each do |addr|
				if addr.main == true
					return addr.street + " " + addr.city
				end
			end
		end
	end
	
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="6u 12u(mobile)">
        <fieldset>
          <label for="name"><span>Nome </span><%= f.text_field :name, id: 'nome' %></label>
          <label for="isbn"><span>ISBN </span><%= f.text_field :isbn, id: 'isbn' %></label>
          <label for="autor"><span>Autor </span><%= f.text_field :author, id: 'autor' %></label>
        </fieldset>
      </div>

      <div class="6u 12u(mobile)">
        <label for="ano"><span>Ano </span><%= f.text_field :year, id: 'ano' %></label>
        <label for="idioma"><span>Idioma </span><%= f.text_field :language, id: 'idioma' %></label>
        <label for="editora"><span>Editora </span><%= f.text_field :publisher, id: 'editora' %></label>
      </div>
    </div>

    <section class="container box feature1">
      <div class="row">
        <div class="12u">
          <%= f.submit "Salvar", class: "button", id: 'salvar' %>
          <%= link_to "Cancelar", books_path, class: "button" %>
        </div>
      </div>
    </section>
<% end %>


<script type="text/javascript">
    $(document).ready(function() { $('#salvar').on('click', function(e){
      var nome = document.getElementById('nome').value;
      var isbn = document.getElementById('isbn').value;
      var autor = document.getElementById('autor').value;
      var ano = document.getElementById('ano').value;
      var idioma = document.getElementById('idioma').value;
      var editora = document.getElementById('editora').value;

      if (nome == "" || autor == "" || ano == "" || idioma == "" || editora == ""){
        alert("Existem campos vazios!");
        e.preventDefault();
        return;
      }

      if (isNaN(ano)){
        alert("Ano deve ser um número!");
        e.preventDefault(); 
        return;
      }

      if (!validaISBN(isbn)){
        alert("ISBN inválido!");
        e.preventDefault(); 
      }
          
    })
  });
  </script>

app/views/books/catalog.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->

<html>
<body class="homepage">
    <div id="page-wrapper">

      <!-- Header -->
        <div id="header-wrapper" style="background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)), url('images/bg03.png'), url('images/bg02.png');"> 
          <div class="container">
            <!-- Header -->
            <% if user_signed_in? %>
			                <%= render 'main/login_top_menu' %>
			            <% else %>
			                <%= render 'main/logout_top_menu' %>
			            <% end %>
          	</div>
        </div>
				
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
								<section class="container box feature1">
									<div class="row" id="bookstoreList">
										<div class="12u">
											<header>
												<h2>Estes são alguns dos títulos em nosso catálogo</h2> <br>
												<div class="row">
													<div class="6u">
													</div>
													<div class="6u">
													<%= link_to "Voltar ao simulador", "/#simular", :class => "button" %>
													</div>
												</div>
												
											</header>
											<% @categories.each do |category| 
												n_books = category.book_categories.count 
												if n_books > 0 
													if n_books < 5 
													 	max = n_books
													else
													 	max = 5
													end %>
												
													<div class="row"><h1> <%= category.name %></h1></div>
														<% category.book_categories[0..max].each do |book| %>
																<% b = Book.find(book.book_id) %>	
											        			<div class="1.5u 6u(mobile)">
												        			<%= image_tag("/images/books_cover/#{b.id}.jpg",:id => "capa") %><br>
																	<span style="font-weight: bold;"> <%= b.name %></span><br>
							        								<span style="font-style: italic;"> <%= b.author %></span><br>
										        				</div>
									        			<% end %>
												<% end %>
											<% end %>
										</div>
									</div>	
								</section>
							</div>
						</div>
					</div>
				</div>
				
			<!-- Footer Wrapper -->
			<%= render 'main/footer' %>

app/views/books/edit.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->
<html xmlns="http://www.w3.org/1999/html">
<head>
  <title>SejaLivro - Assinatura Literária</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
  <link rel="stylesheet" href="assets/css/main.css" />
  <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
  <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
  </script>
</head>
<body class="homepage">
<div id="page-wrapper">

  <!-- Header -->
  <!-- Header -->
        <div id="header-wrapper">
          <div class="container">
            <!-- Header -->
              <% if user_signed_in? %>
                      <%= render 'main/login_top_menu' %>
                  <% else %>
                      <%= render 'main/logout_top_menu' %>
                  <% end %>
          </div>
        </div>

  <!-- Main Wrapper -->
  <div id="main-wrapper">
    <div class="wrapper style3">
      <div class="inner">
        <div class="container">
          <section class="container box feature1">
            <div class="row" id="createBook">
              <div class="12u">
                <header>
                  <h2>Editar item</h2>
                </header>
              </div>
            </div>
          </section>
          <%= render 'form', book: @book %>
        </div>
      </div>
    </div>
  </div>
</div>

    <%= render 'main/footer' %>

  <!-- Scripts -->

  <script src="assets/js/jquery.min.js"></script>
  <script src="assets/js/jquery.dropotron.min.js"></script>
  <script src="assets/js/skel.min.js"></script>
  <script src="assets/js/skel-viewport.min.js"></script>
  <script src="assets/js/util.js"></script>
  <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
  <script src="assets/js/main.js"></script>

</body>
</html>

app/views/books/index.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->
<html>
<head>
  <title>SejaLivro - Assinatura Literária</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
  <link rel="stylesheet" href="assets/css/main.css" />
  <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
  <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
  </script>
</head>
<body class="homepage">
<div id="page-wrapper">

  <!-- Header -->
  <div id="header-wrapper">
    <div class="container">
      <!-- Header -->
      <% if user_signed_in? %>
          <%= render 'main/login_top_menu' %>
      <% else %>
          <%= render 'main/logout_top_menu' %>
      <% end %>
    </div>
  </div>

  <!-- Main Wrapper -->
  <div id="main-wrapper">
    <div class="wrapper style3">
      <div class="inner">
        <div class="container">
          <section class="container box feature1">
            <div class="row" id="bookList">
              <div class="12u">
                <header>
                  <h2>Livros</h2>
                  <div class="row" style="vertical-align: bottom;">
                    <div class="6u" style="vertical-align: middle;">
                      <%= form_tag search_books_path do %>
                          <%= label_tag(:q, "Buscar livros pelo nome:") %>
                          <input type="search" id="search" placeholder="Buscar livros" type="text" name="query">
                          <%= submit_tag("Buscar") %>
                      <% end %>
                    </div>

                    <div class="6u" style="line-height: 100%;">
                      <%= link_to 'Adicionar livro', new_book_path, class: "button" %>
                    </div>
                  </div>
                </header>

                <% if @books.count ==  0 and @q == nil%>
                    <span style="font-weight: bold;"> Não possui itens. </span><br>
                <% else %>
                    <div class="row">
                      <div class="1u">
                        <b>ID</b>
                      </div>
                      <div class="1u">
                        <b>Nome</b>
                      </div>
                      <div class="1u">
                        <b>ISBN</b>
                      </div>
                      <div class="1u">
                        <b>Autor</b>
                      </div>
                      <div class="1u">
                        <b>Ano</b>
                      </div>
                      <div class="1u">
                        <b>Idioma</b>
                      </div>
                      <div class="1u">
                        <b>Editora</b>
                      </div>
                      <div class="5u">
                        <b>Ações</b>
                      </div>
                    </div>
                    <% if @books.count == 0 and @q != nil %>
                        <div class="row">
                          <div class="12u">
                            <h2>
                              <%= "Não há livros cadastrados com esse nome" %>
                            </h2>
                          </div>
                        </div>
                        <div class="row">
                          <div class="12u">
                            <%= link_to "Voltar", "/books/", :class => "button" %>
                          </div>
                        </div>
                    <% end %>
                    <% @books.each do |b| %>
                        <div class="row">
                          <div class="1u">
                            <%= b.id %>
                          </div>
                          <div class="1u">
                            <%= b.name %>
                          </div>
                          <div class="1u">
                            <%= b.isbn %>
                          </div>
                          <div class="1u">
                            <%= b.author %>
                          </div>
                          <div class="1u">
                            <%= b.year %>
                          </div>
                          <div class="1u">
                            <%= b.language %>
                          </div>
                          <div class="1u">
                            <%= b.publisher %>
                          </div>
                          <div class="5u">
								<span> 
	                          		<%= link_to 'Editar', edit_book_path(b), class: "button" %>
                  <%= link_to 'Excluir', b, method: :delete, class: "button" %>
	                          		</span>
                          </div>
                        </div>
                    <% end %>
                <% end %>
              </div>
            </div>
          </section>
          </section>
        </div>
      </div>
    </div>
  </div>


  <!-- Footer Wrapper -->
<%= render 'main/footer' %>

app/views/books/new.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->
<html xmlns="http://www.w3.org/1999/html">
	<head>
		<title>SejaLivro - Assinatura Literária</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				       <div id="header-wrapper">
          <div class="container">
            <!-- Header -->
              <% if user_signed_in? %>
                      <%= render 'main/login_top_menu' %>
                  <% else %>
                      <%= render 'main/logout_top_menu' %>
                  <% end %>
          </div>
        </div>
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
							<section class="container box feature1">
									<div class="row" id="createBook">
										<div class="12u">
											<header>
												<h2>Adicionar item</h2>
											</header>
										</div>
									</div>
							</section>
              <%= render 'form', book: @book %>
						</div>
					</div>
				</div>
			</div>

			<!-- Footer Wrapper -->
			<%= render 'main/footer' %>

app/views/books/show.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->
<html>
	<head>
		<title>SejaLivro - Assinatura Literária</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div class="container">
						<!-- Header -->
							<% if user_signed_in? %>
			                <%= render 'main/login_top_menu' %>
			            <% else %>
			                <%= render 'main/logout_top_menu' %>
			            <% end %>
					</div>
				</div>
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
							<section class="container box feature1">
									<div class="row" id="viewBook">
										<div class="12u">
											<header>
												<h2>Visualizar item</h2>
											</header>
										</div>
									</div>
							</section>
								<div class="row">
									<div class="6u 12u(mobile)" style="text-align:right">
										<%= image_tag("/images/books_cover/#{@book.id}.jpg",  float:'right', width:'auto', height:'400') %>
									</div>
									<div class="6u 12u(mobile)">
										<dl class="inline">
											<dt>ID:</dt>
											<dd><%= @book.id %></dd>
											<dt>Nome:</dt>
											<dd><%= @book.name %></dd>
											<dt>ISBN:</dt>
											<dd><%= @book.isbn %></dd>
											<dt>Autor:</dt>
											<dd><%= @book.author %></dd>
											<dt>Ano:</dt>
											<dd><%= @book.year %></dd>
											<dt>Idioma:</dt>
											<dd><%= @book.language %></dd>
											<dt>Editora:</dt>
											<dd><%= @book.publisher %></dd>
										</dl>
									</div>
								</div>
								<section class="container box feature1">
									<div class="row">
										<div class="12u">
											<span> <%= link_to 'Voltar', books_path, class: "button" %>
                          							<%= link_to 'Editar', edit_book_path(@book), class: "button" %>
                          							<%= link_to 'Excluir', @book, method: :delete, class: "button" %>
											  </span>
										</div>
									</div>
								</section>
							</div>
						</div>
					</div>
				</div>

				<div class="12u">
											<header>
												<h2></h2>
											</header>

											<footer>

											</footer>
										</div>
									</div>
							  </section>
							</div>
						</div>
					</div>
				</div>

			<!-- Footer Wrapper -->
			<%= render 'main/footer' %>