config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {
      sign_in: 'login', registration: 'cadastro'
  }

  resources :bookstores, :categories, :books
  resources :admin, :signature
  
  root 'main#index'

  get '/cadastro', to: 'users#new', as: 'users'  
  get '/logout', to: 'users#logout'
  get '/pagamento', to: 'signature#payment'
  get '/profile/:id/edit', to: 'users#edit', as: 'edit_user'    
  get 'profile/:id/address', to: 'address#edit', as: 'edit_address'  
  get '/profile/:id', to: 'users#profile', as: 'profile'
  get '/my_books/:id', to: 'users#my_books', as: 'my_books'
  get '/catalog' => 'books#catalog', as: 'books_catalog'
  get '/packages' => 'admin#packages', as: 'admin_packages'
  get '/boleto_payment' => 'signature#boleto_payment'
  get '/credit_card_payment' => 'signature#credit_card_payment'
  post '/cadastro', to: 'users#create'
  post 'bookstores/search' => 'bookstores#search', as: 'search_bookstores'
  post 'books/search' => 'books#search', as: 'search_books'
  post 'categories/search' => 'categories#search', as: 'search_categories'
  post '/credit_card_payment' => 'signature#process_payment_credit_card'
  post '/boleto_payment' => 'signature#process_payment_boleto'
  post '/cadastro' => 'users#create'

  post '/signature/cancel_signature/:id' => 'signature#cancel_signature'
  post '/users/delete_user/:id' => 'users#delete_user'

  post '/' => 'main#store_signature'

  patch '/profile/:id/edit', to: 'users#update', as: 'update_user'
  patch 'profile/:id/address', to: 'address#update', as: 'address_update'  

  delete 'profile/:id', to: 'users#destroy', as: 'delete_user'

end

app/models/address.rb
class Address < ActiveRecord::Base

  # Relações
  belongs_to :user, dependent: :destroy

  # Validação
  validates :user_id, :zipcode, :street, :presence => true

end

app/models/book.rb
class Book < ActiveRecord::Base



    has_many :user_books, :class_name => 'UserBook'
    has_many :package_books, :class_name => 'PackageBook'
    has_many :bookstore_books, :class_name => 'BookstoreBook'
    has_many :book_categories, :class_name => 'BookCategory'
end

app/models/book_category.rb
class BookCategory < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :category, :class_name => 'Category', :foreign_key => :id_category
end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base



    has_many :user_books, :class_name => 'UserBook'
    has_many :orders, :class_name => 'Order'
    has_many :bookstore_books, :class_name => 'BookstoreBook'
end

app/models/bookstore_book.rb
class BookstoreBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :bookstore, :class_name => 'Bookstore', :foreign_key => :id_bookstore
end

app/models/category.rb
class Category < ActiveRecord::Base



    has_many :user_preferences, :class_name => 'UserPreference'
    has_many :book_categories, :class_name => 'BookCategory'
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base

    has_many :payments, :class_name => 'Payment'
    belongs_to :user, :class_name => 'User', :foreign_key => :user_id

end

app/models/order.rb
class Order < ActiveRecord::Base



    belongs_to :bookstore, :class_name => 'Bookstore', :foreign_key => :id_bookstore
    has_many :packages, :class_name => 'Package'
end

app/models/package.rb
class Package < ActiveRecord::Base



    belongs_to :order, :class_name => 'Order', :foreign_key => :id_order
    has_many :package_books, :class_name => 'PackageBook'
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/package_book.rb
class PackageBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :package, :class_name => 'Package', :foreign_key => :id_package
end

app/models/payment.rb
class Payment < ActiveRecord::Base



    belongs_to :credit_card, :class_name => 'CreditCard', :foreign_key => :id_credit_card
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/periodicity.rb
class Periodicity < ActiveRecord::Base



end

app/models/signature.rb
class Signature < ActiveRecord::Base
    belongs_to :user, :class_name => 'User', :foreign_key => :user_id
end

app/models/support_ticket.rb
class SupportTicket < ActiveRecord::Base


    self.inheritance_column = :ruby_type
    belongs_to :user, :class_name => 'User', :foreign_key => :id_user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    enum gender: [ :masculino, :feminino ]

    has_many :addresses, :class_name => 'Address'
    accepts_nested_attributes_for :addresses

    has_many :user_preferences, :class_name => 'UserPreference'
    has_many :user_books, :class_name => 'UserBook'
    has_many :support_tickets, :class_name => 'SupportTicket'
    has_many :signatures, :class_name => 'Signature'
    has_many :payments, :class_name => 'Payment'
    has_many :packages, :class_name => 'Package'
    has_many :credit_cards, :class_name => 'CreditCard'

    validates :password, confirmation: true

  validates :name, :cpf, :email, :birth_date, :gender, presence: true
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base



    belongs_to :book, :class_name => 'Book', :foreign_key => :id_book
    belongs_to :user, :class_name => 'Bookstore', :foreign_key => :id_user
end

app/controllers/bookstores_controller.rb
class BookstoresController < ApplicationController

  def new
    @bookstore = Bookstore.new
  end

  # GET /books/1/edit
  def edit
    @bookstore = Bookstore.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @bookstore = Bookstore.new(bookstore_params)

    respond_to do |format|
      if @bookstore.save
        format.html { redirect_to action: :index }
        format.json { render :index, status: :created, location: @bookstore }
      else
        format.html { render :new }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @bookstore = Bookstore.find(params[:id])
    @bookstore_books = @bookstore.bookstore_books
    @bookstore_orders = @bookstore.orders
  end 

  def index
    if user_signed_in?
      @bookstores = Bookstore.all.order(:id)
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /bookstore/1
  # PATCH/PUT /bookstore/1.json
  def update
    @bookstore = Bookstore.find(params[:id])
    respond_to do |format|
      if @bookstore.update(bookstore_params)
        format.html { redirect_to action: :index }
        format.json { render :index, status: :ok, location: @bookstore }
      else
        format.html { render :edit }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookstore/1
  # DELETE /bookstore/1.json
  def destroy
    @bookstore = Bookstore.find(params[:id])
    @bookstore.destroy
    respond_to do |format|
      format.html { redirect_to bookstores_url }
      format.json { head :no_content }
    end
  end

  def search
    @q = "%#{params[:query]}%"
    @bookstores = Bookstore.where("lower(name) LIKE ?", @q.downcase).order(:id)
    render 'index'
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def bookstore_params
    params.require(:bookstore).permit(:name, :telephone, :cnpj)
  end

end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def full_address
		if @user_addresses.count == 0
			"Endereço não informado"
		else
			@user_addresses.each do |addr|
				if addr.main == true
					return addr.street + " " + addr.city
				end
			end
		end
	end
	
end

app/views/bookstores/_form.html.erb
<%= form_for(bookstore) do |f| %>
    <% if bookstore.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this bookstore from being saved:</h2>

          <ul>
            <% bookstore.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label 'Nome' %>
      <%= f.text_field :name, id: 'nome' %>
    </div>

    <div class="field">
      <%= f.label 'Telefone' %>
      <%= f.text_field :telephone, id:'telefone' %>
    </div>

    <div class="field">
      <%= f.label 'CNPJ' %>
      <%= f.text_field :cnpj, id: 'cnpj' %>
    </div>

    <div class="actions">
      <%= f.submit "Salvar", id: 'salvar' %>
      <%= link_to "Cancelar", bookstores_path, class: "button" %>
    </div>
<% end %>

app/views/bookstores/edit.html.erb
<html>
	<head>
		<title>SejaLivro - Assinatura Literária</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div class="container">
						<!-- Header -->
							<% if user_signed_in? %>
			                <%= render 'main/login_top_menu' %>
			            <% else %>
			                <%= render 'main/logout_top_menu' %>
			            <% end %>
					</div>
				</div>
				<div id="main-wrapper">
					<div class="wrapper style2">
						<div class="inner">

							<!-- Feature 1 -->
								<section class="container box feature1">
									<div class="row" id="vantagens">
										<div class="4u 12u(mobile)"></div>
										<div class="4u 12u(mobile)">
											<section>
												<h1>Editando livraria</h1>
												<%= render 'form', bookstore: @bookstore %>
											</section>
										</div>
										<div class="4u 12u(mobile)"></div>
									</div>
								</section>
							</div>
						</div>
					</div>
				</div>


	<%= render 'main/footer' %>

	<script type="text/javascript">
    $(document).ready(function() { $('#salvar').on('click', function(e){
      if (!validateBookstore())
          e.preventDefault();
    })
  });
  </script>
	

app/views/bookstores/index.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->

<html>
<body class="homepage">
    <div id="page-wrapper">

      <!-- Header -->
        <div id="header-wrapper" style="background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)), url('images/bg03.png'), url('images/bg02.png');"> 
          <div class="container">
            <!-- Header -->
            <% if user_signed_in? %>
			                <%= render 'main/login_top_menu' %>
			            <% else %>
			                <%= render 'main/logout_top_menu' %>
			            <% end %>
          	</div>
        </div>
				
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
								<section class="container box feature1">
									<div class="row" id="bookstoreList">
										<div class="12u">
											<header>
												<h2>Livrarias</h2> <br>
												<div class="row">
													<div class="6u">
													<%= form_tag search_bookstores_path do %>
													<%= label_tag(:q, "Buscar livraria pelo nome:") %>
													<input type="search" id="search" placeholder="Buscar livrarias" type="text" name="query">
													<%= submit_tag("Buscar") %>
													<% end %>
													</div>
													<div class="6u">
													<%= link_to "Adicionar livraria", "/bookstores/new", :class => "button" %>
													</div>
												</div>
												
											</header>
											<div class="row"> 
												<div class="1u"> 
													<b>ID</b>
												</div>
												<div class="2u"> 
													<b>NAME</b>
												</div>
												<div class="2u"> 
													<b>CNPJ</b>
												</div>
												<div class="2u"> 
													<b>Telephone</b>
												</div>
												<div class="5u"> 
													<b>Options</b>
												</div>
											</div>
											<% if @bookstores.count == 0 and @q != nil %>
												<div class="row"> 
													<div class="12u">
														<h2>
															<%= "Não há livrarias cadastradas com esse nome" %>
														</h2>
													</div>
												</div>
												<div class="row"> 
													<div class="12u">
														<%= link_to "Voltar", "/bookstores/", :class => "button" %>
														</div>
												</div>
											<% end %>
											<% @bookstores.each do |bookstore| %>
												<div class="row"> 
													<div class="1u"> 
														<%= bookstore.id %>
													</div>
													<div class="2u"> 
														<%= bookstore.name %>
													</div>
													<div class="2u"> 
														<%= bookstore.cnpj %>
													</div>
													<div class="2u"> 
														<%= bookstore.telephone %>
													</div>
													<div class="5u"> 
                            <span>
                              <%= link_to "Editar", "/bookstores/#{bookstore.id.to_s}/edit/", :class => "button" %>
                              <%= link_to 'Excluir', bookstore, method: :delete, class: "button" %>
                            </span>
													</div>
												</div>
											<% end %>	
										</div>
									</div>	
								</section>
							</div>
						</div>
					</div>
				</div>
				
			<!-- Footer Wrapper -->
			<%= render 'main/footer' %>

app/views/bookstores/show.html.erb
<!DOCTYPE HTML>
<!--
	ZeroFour by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
	oi
-->
<html>
	<head>
		<title>SejaLivro - Assinatura Literária</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
							<!-- Header -->
          <div id="header-wrapper" style="background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.5)), url('images/bg03.png'), url('images/bg02.png');"> 
          <div class="container">
            <!-- Header -->
            <% if user_signed_in? %>
			                <%= render 'main/login_top_menu' %>
			            <% else %>
			                <%= render 'main/logout_top_menu' %>
			            <% end %>
          	</div>
        </div>
				
			<!-- Main Wrapper -->
				<div id="main-wrapper">
					<div class="wrapper style3">
						<div class="inner">
							<div class="container">
							<section class="container box feature1">
									<div class="row" id="viewBookstore">
										<div class="12u">
											<header>
												<h2>Visualizando Livraria <%= @bookstore.name %></h2>
											</header>
										</div>
									</div>
										<div class="row">
											<div class="4u">
												<h1>Dados</h1>
												<dl class="inline">
													<dt>ID:</dt>
													<dd><%= @bookstore.id %></dd>
													<dt>Nome:</dt>
													<dd><%= @bookstore.name %></dd>
													<dt>CNPJ:</dt>
													<dd><%= @bookstore.cnpj %></dd>
													<dt>Telefone:</dt>
													<dd><%= @bookstore.telephone %></dd>
													<!--<dt>E-mail:</dt>
													<dd>E-mail da Livraria</dd>		-->									
												</dl>

												<span> 
														<%= link_to "Voltar", "/bookstores", :class => "button" %>
														<%= link_to "Editar", "/bookstores/#{@bookstore.id.to_s}/edit/", :class => "button" %>
														<%= link_to "Deletar", "/bookstores/#{@bookstore.id.to_s}/del/", :class => "button" %>
												</span>
											</div>

											<div class="4u">
												<h1>Pedidos</h1>
													<% if @bookstore_orders.count == 0 %>
														 <dt>Não há registro de pedidos</dt>
												<% else %>
													<dl class="inline">
														<dt>Data </dt>
														<dt>Status </dt>
													</dl>
													<% @bookstore_orders.each do |order| %>
														<dl class="inline">
															<dd><%= order.date.to_formatted_s(:rfc822) %></dd>
															<dd><%= order.status %></dd>
														</dl>
													<% end %>
												<% end %>



											</div>

											<div class="4u">
												<h1>Catálogo</h1>
													<% if @bookstore_books.count == 0 %>
														 <dt>Não há livros no catálogo</dt>
												<% else %>
													<div class="row"> 
													<div class="1u">ID</div>
													<div class="4u">Título</div>
													<div class="4u">Autor</div>
													<div class="1u">Estoque</div>
													</div>
			
													<% @bookstore_books.each do |book| %>
														<% b = Book.find(book.book_id) %>
														
														<div class="row">		

													<div class="1u"><%= b.id %></div>
													<div class="4u"><%= b.name %></div>
													<div class="4u"><%= b.author %></div>
													<div class="1u"><%= book.stock %></div>
													</div>
													<% end %>
												<% end %>
											</div>


										</div>
			
								</section>								
							</div>
						</div>
					</div>
				</div>

			<!-- Footer Wrapper -->
				<%= render 'main/footer' %>